# Generated by Django 3.0.7 on 2020-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_cards_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='slug',
            field=models.SlugField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
