# Generated by Django 3.0.7 on 2020-06-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_cards_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='nonce',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
