# Generated by Django 3.0.7 on 2020-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_entry_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='nonce',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
