# Generated by Django 3.0.7 on 2020-06-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cards_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='slug',
        ),
    ]
